import { customAlphabet } from "nanoid";
import type { Group, Option } from "@/lib/types";

const nano = customAlphabet(
  "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",
  28,
);

/** Stable demo tokens (URL-safe, 28 chars). Regenerate in admin for production. */
export const FRENCH_TOKEN = "FrMumsK7x9Qp2mNv4Lw8Rj3Hs6YbCd";
export const BARNES_TOKEN = "BaMumsT3n8Wc5Kd1Mf9Zx7Pq4JuRvEh";

export function newToken(): string {
  return nano();
}

export function googleTicketsUrl(title: string, venue?: string | null): string {
  const q = encodeURIComponent(`${title}${venue ? ` ${venue}` : ""} tickets`);
  return `https://www.google.com/search?q=${q}`;
}

export const SEED_GROUPS: Group[] = [
  {
    id: "french",
    name: "French Mums",
    invite_token: FRENCH_TOKEN,
    start_time: "19:00:00",
    arrival_note: "7pm start",
    subtitle: "Evenings from 7pm",
    evenings: [2, 3, 4],
    lead_days: 11,
    horizon_days: 28,
    vote_hours: 24,
    show_budget: 50,
    area_label:
      "Central London. Members live in Barnes, Clapham, West Hampstead",
    preferred_lines: ["northern", "victoria", "district", "hammersmith"],
    supports_day_meetups: false,
  },
  {
    id: "barnes",
    name: "Barnes Mums",
    invite_token: BARNES_TOKEN,
    start_time: "20:00:00",
    arrival_note: "Arrive any time from 8pm, after bedtime",
    subtitle: "Evenings from 8pm · Day walks",
    evenings: [2, 3, 4],
    lead_days: 11,
    horizon_days: 28,
    vote_hours: 24,
    show_budget: null,
    area_label: "Barnes, between Church Road (Riva) and White Hart Lane",
    preferred_lines: [],
    supports_day_meetups: true,
  },
];

type SeedOption = Omit<
  Option,
  "id" | "status" | "seen" | "seen_on" | "open_days" | "availability_note"
> & {
  id?: string;
  open_days?: number[] | null;
  availability_note?: string | null;
};

function frenchShow(
  partial: {
    title: string;
    venue: string;
    station?: string | null;
    area?: string | null;
    lines: string[];
    price_from?: number | null;
    runs_from?: string | null;
    runs_to?: string | null;
    url?: string | null;
    note?: string | null;
    is_new?: boolean;
    upcoming?: boolean;
    flexible_arrival?: boolean;
  },
): SeedOption {
  return {
    group_id: "french",
    kind: "show",
    venue: partial.venue,
    area: partial.area ?? null,
    station: partial.station ?? null,
    lines: partial.lines,
    price_from: partial.price_from ?? null,
    runs_from: partial.runs_from ?? null,
    runs_to: partial.runs_to ?? null,
    url: partial.url ?? googleTicketsUrl(partial.title, partial.venue),
    note: partial.note ?? null,
    is_new: partial.is_new ?? false,
    upcoming: partial.upcoming ?? false,
    flexible_arrival: partial.flexible_arrival ?? true,
    title: partial.title,
  };
}

export const SEED_OPTIONS: SeedOption[] = [
  // French shows
  frenchShow({
    title: "Hadestown",
    venue: "Lyric Theatre",
    station: "Piccadilly Circus / Leicester Sq",
    lines: ["northern", "piccadilly", "bakerloo"],
    price_from: 30,
    runs_to: "2027-06-27",
  }),
  frenchShow({
    title: "Hamilton",
    venue: "Victoria Palace Theatre",
    station: "Victoria",
    lines: ["victoria", "district", "circle"],
    price_from: 24,
    runs_to: "2027-10-02",
  }),
  frenchShow({
    title: "Wicked",
    venue: "Apollo Victoria Theatre",
    station: "Victoria",
    lines: ["victoria", "district", "circle"],
    price_from: 29.5,
    runs_to: "2027-05-30",
  }),
  frenchShow({
    title: "Les Misérables",
    venue: "Sondheim Theatre",
    station: "Leicester Sq / Piccadilly Circus",
    lines: ["northern", "piccadilly"],
    price_from: 30,
    runs_to: "2027-10-02",
  }),
  frenchShow({
    title: "The Book of Mormon",
    venue: "Prince of Wales Theatre",
    station: "Leicester Sq / Piccadilly Circus",
    lines: ["northern", "piccadilly"],
    price_from: 24,
    runs_to: "2027-01-23",
  }),
  frenchShow({
    title: "The Phantom of the Opera",
    venue: "His Majesty's Theatre",
    station: "Piccadilly Circus / Charing Cross",
    lines: ["northern", "piccadilly", "bakerloo"],
    price_from: 30,
    runs_to: "2027-03-13",
  }),
  frenchShow({
    title: "Mamma Mia!",
    venue: "Novello Theatre",
    station: "Covent Garden / Temple",
    lines: ["piccadilly", "district"],
    price_from: 21,
    runs_to: "2027-03-13",
  }),
  frenchShow({
    title: "Moulin Rouge! The Musical",
    venue: "Piccadilly Theatre",
    station: "Piccadilly Circus",
    lines: ["piccadilly", "bakerloo"],
    price_from: 29.27,
    runs_to: "2027-02-14",
  }),
  frenchShow({
    title: "Oliver!",
    venue: "Gielgud Theatre",
    station: "Piccadilly Circus / Leicester Sq",
    lines: ["northern", "piccadilly"],
    price_from: 24,
    runs_to: "2027-03-14",
  }),
  frenchShow({
    title: "Matilda The Musical",
    venue: "Cambridge Theatre",
    station: "Covent Garden / Leicester Sq",
    lines: ["northern", "piccadilly"],
    price_from: 24,
    runs_to: "2027-09-05",
  }),
  frenchShow({
    title: "The Devil Wears Prada",
    venue: "Dominion Theatre",
    station: "Tottenham Court Road",
    lines: ["northern", "central", "elizabeth"],
    price_from: 30,
    runs_to: "2027-09-25",
  }),
  frenchShow({
    title: "Titanique",
    venue: "Criterion Theatre",
    station: "Piccadilly Circus",
    lines: ["piccadilly", "bakerloo"],
    price_from: 30,
    runs_to: "2027-01-03",
  }),
  frenchShow({
    title: "Cabaret",
    venue: "Kit Kat Club at the Playhouse",
    station: "Embankment",
    lines: ["northern", "district", "bakerloo"],
    price_from: 40.98,
    runs_to: "2027-01-30",
  }),
  frenchShow({
    title: "Into the Woods",
    venue: "Noël Coward Theatre",
    station: "Leicester Square",
    lines: ["northern", "piccadilly"],
    price_from: 18,
    runs_to: "2027-01-09",
  }),
  frenchShow({
    title: "RENT",
    venue: "Tom Stoppard Theatre",
    station: "Leicester Square",
    lines: ["northern", "piccadilly"],
    price_from: 29.27,
    runs_to: "2027-03-27",
    is_new: true,
  }),
  frenchShow({
    title: "Jesus Christ Superstar",
    venue: "Theatre Royal Drury Lane",
    station: "Covent Garden / Holborn",
    lines: ["piccadilly", "central"],
    price_from: 25,
    runs_from: "2026-10-16",
    runs_to: "2027-01-09",
    is_new: true,
  }),
  frenchShow({
    title: "Avenue Q",
    venue: "Shaftesbury Theatre",
    station: "Holborn / Tottenham Court Rd",
    lines: ["northern", "central", "piccadilly"],
    price_from: 30,
    runs_to: "2027-01-03",
  }),
  frenchShow({
    title: "SIX",
    venue: "Vaudeville Theatre",
    station: "Charing Cross / Embankment",
    lines: ["northern", "bakerloo", "district"],
    price_from: 34.5,
    runs_to: "2027-11-28",
  }),
  frenchShow({
    title: "Sinatra The Musical",
    venue: "Aldwych Theatre",
    station: "Temple / Covent Garden",
    lines: ["district", "piccadilly"],
    price_from: 42,
    runs_to: "2027-04-10",
  }),
  frenchShow({
    title: "Paddington The Musical",
    venue: "Savoy Theatre",
    station: "Charing Cross / Embankment",
    lines: ["northern", "bakerloo", "district"],
    price_from: 40.98,
    runs_to: "2028-02-13",
  }),
  frenchShow({
    title: "The Lion King",
    venue: "Lyceum Theatre",
    station: "Covent Garden / Temple",
    lines: ["piccadilly", "district"],
    price_from: 40.6,
    runs_to: "2027-05-16",
  }),
  frenchShow({
    title: "One Day The Musical",
    venue: "Garrick Theatre",
    station: "Leicester Square",
    lines: ["northern", "piccadilly"],
    price_from: 36,
    runs_from: "2026-11-17",
    runs_to: "2027-03-14",
    is_new: true,
  }),
  frenchShow({
    title: "Pride The Musical",
    venue: "Bridge Theatre",
    station: "London Bridge",
    lines: ["northern", "jubilee"],
    price_from: 34.2,
    runs_from: "2026-11-12",
    runs_to: "2027-05-08",
    is_new: true,
  }),
  frenchShow({
    title: "Kimberly Akimbo",
    venue: "Hampstead Theatre",
    station: "Swiss Cottage (Belsize Park 10 min)",
    lines: ["jubilee", "northern"],
    price_from: 42,
    runs_to: "2026-11-07",
    is_new: true,
    note: "European premiere of the Tony winner",
  }),
  frenchShow({
    title: "Martin Guerre",
    venue: "The Old Vic",
    station: "Waterloo",
    lines: ["northern", "bakerloo", "jubilee"],
    price_from: 29,
    runs_from: "2026-10-01",
    runs_to: "2026-10-31",
    is_new: true,
    note: "Semi-staged, from the Les Mis writers",
  }),
  frenchShow({
    title: "Ceilidh",
    venue: "Shoreditch Town Hall",
    station: "Old Street",
    lines: ["northern"],
    price_from: null,
    runs_from: "2026-10-23",
    runs_to: "2026-11-13",
    is_new: true,
  }),
  frenchShow({
    title: "Franz & Marie",
    venue: "Charing Cross Theatre",
    station: "Embankment",
    lines: ["northern", "district", "bakerloo"],
    price_from: 20.5,
    runs_to: "2026-11-14",
    is_new: true,
  }),
  frenchShow({
    title: "Billy Elliot",
    venue: "Adelphi Theatre",
    station: "Charing Cross / Embankment",
    lines: ["northern", "bakerloo", "district"],
    price_from: null,
    runs_from: "2027-02-12",
    runs_to: "2027-07-31",
    is_new: true,
    upcoming: true,
  }),
  frenchShow({
    title: "Singin' in the Rain",
    venue: "Sadler's Wells",
    station: "Angel",
    lines: ["northern"],
    price_from: null,
    runs_from: "2027-06-02",
    runs_to: "2027-07-03",
    is_new: true,
    upcoming: true,
  }),
  // French food
  {
    group_id: "french",
    kind: "food",
    title: "Supawan",
    venue: "Thai · King's Cross",
    area: "King's Cross",
    station: "King's Cross St Pancras",
    lines: ["northern", "victoria", "piccadilly"],
    price_from: null,
    runs_from: null,
    runs_to: null,
    url: googleTicketsUrl("Supawan", "King's Cross"),
    note: "Punchy Thai, good for groups",
    is_new: false,
    upcoming: false,
    flexible_arrival: true,
  },
  {
    group_id: "french",
    kind: "food",
    title: "Hoppers",
    venue: "Sri Lankan · King's Cross",
    area: "King's Cross",
    station: "King's Cross St Pancras",
    lines: ["northern", "victoria", "piccadilly"],
    price_from: null,
    runs_from: null,
    runs_to: null,
    url: googleTicketsUrl("Hoppers", "King's Cross"),
    note: "Good for groups and veggies",
    is_new: false,
    upcoming: false,
    flexible_arrival: true,
  },
  {
    group_id: "french",
    kind: "food",
    title: "La Chingada",
    venue: "Mexican · Euston",
    area: "Euston",
    station: "Euston",
    lines: ["northern", "victoria"],
    price_from: null,
    runs_from: null,
    runs_to: null,
    url: googleTicketsUrl("La Chingada", "Euston"),
    note: "Relaxed tacos and margaritas",
    is_new: false,
    upcoming: false,
    flexible_arrival: true,
  },
  {
    group_id: "french",
    kind: "food",
    title: "Firin",
    venue: "Turkish · King's Cross",
    area: "King's Cross",
    station: "King's Cross St Pancras",
    lines: ["northern", "victoria", "piccadilly"],
    price_from: null,
    runs_from: null,
    runs_to: null,
    url: googleTicketsUrl("Firin", "King's Cross"),
    note: "Bright room, slow-cooked kebab",
    is_new: false,
    upcoming: false,
    flexible_arrival: true,
  },
  // Barnes
  {
    group_id: "barnes",
    kind: "drinks",
    title: "The Crossing",
    venue: "Pub & restaurant, White Hart Lane",
    area: "White Hart Lane",
    station: null,
    lines: [],
    price_from: null,
    runs_from: null,
    runs_to: null,
    url: googleTicketsUrl("The Crossing", "White Hart Lane Barnes"),
    note: "Bar area at the front, garden terrace, upstairs room for groups",
    is_new: false,
    upcoming: false,
    flexible_arrival: true,
  },
  {
    group_id: "barnes",
    kind: "drinks",
    title: "Harty's",
    venue: "Deli, wine shop & bar, 78 White Hart Lane",
    area: "White Hart Lane",
    station: null,
    lines: [],
    price_from: null,
    runs_from: null,
    runs_to: null,
    url: googleTicketsUrl("Harty's", "White Hart Lane Barnes"),
    note: "Easy glass of wine, drop in when you can",
    is_new: false,
    upcoming: false,
    flexible_arrival: true,
    // Wine bar evenings per hartysbarnes.com (coffee shop daytime is separate)
    open_days: [4, 5, 6],
    availability_note: "Wine bar Thu–Sat from 5pm — closed Tue/Wed evenings",
  },
  {
    group_id: "barnes",
    kind: "food",
    title: "Omm",
    venue: "Lebanese, 36–38 White Hart Lane",
    area: "White Hart Lane",
    station: null,
    lines: [],
    price_from: null,
    runs_from: null,
    runs_to: null,
    url: googleTicketsUrl("Omm", "White Hart Lane Barnes"),
    note: "Mezze to share, good for staggered arrivals",
    is_new: false,
    upcoming: false,
    flexible_arrival: true,
  },
  {
    group_id: "barnes",
    kind: "food",
    title: "Camile Thai",
    venue: "Thai, 36–38 White Hart Lane",
    area: "White Hart Lane",
    station: null,
    lines: [],
    price_from: null,
    runs_from: null,
    runs_to: null,
    url: googleTicketsUrl("Camile Thai", "White Hart Lane Barnes"),
    note: "Vegan, lactose-free and gluten-free options",
    is_new: false,
    upcoming: false,
    flexible_arrival: true,
  },
  {
    group_id: "barnes",
    kind: "drinks",
    title: "The White Hart",
    venue: "Riverside pub, The Terrace",
    area: "The Terrace",
    station: null,
    lines: [],
    price_from: null,
    runs_from: null,
    runs_to: null,
    url: googleTicketsUrl("The White Hart", "The Terrace Barnes"),
    note: "Big riverside pub with terraces",
    is_new: false,
    upcoming: false,
    flexible_arrival: true,
  },
  {
    group_id: "barnes",
    kind: "drinks",
    title: "The Bull's Head",
    venue: "Pub, 373 Lonsdale Road",
    area: "The Terrace",
    station: null,
    lines: [],
    price_from: null,
    runs_from: null,
    runs_to: null,
    url: googleTicketsUrl("The Bull's Head", "Barnes"),
    note: "Use the bar, not the ticketed jazz room",
    is_new: false,
    upcoming: false,
    flexible_arrival: true,
  },
  {
    group_id: "barnes",
    kind: "drinks",
    title: "Coach and Horses",
    venue: "Pub, 27 Barnes High Street",
    area: "Barnes High Street",
    station: null,
    lines: [],
    price_from: null,
    runs_from: null,
    runs_to: null,
    url: googleTicketsUrl("Coach and Horses", "Barnes High Street"),
    note: "Real ales, wines and gins",
    is_new: false,
    upcoming: false,
    flexible_arrival: true,
  },
  {
    group_id: "barnes",
    kind: "food",
    title: "Base Face Pizza",
    venue: "Pizzeria, 35a Barnes High Street",
    area: "Barnes High Street",
    station: null,
    lines: [],
    price_from: null,
    runs_from: null,
    runs_to: null,
    url: googleTicketsUrl("Base Face Pizza", "Barnes"),
    note: "Slow-dough pizza, casual",
    is_new: false,
    upcoming: false,
    flexible_arrival: true,
  },
  {
    group_id: "barnes",
    kind: "food",
    title: "Home SW13",
    venue: "Modern British, 92–94 Church Road",
    area: "Church Road",
    station: null,
    lines: [],
    price_from: null,
    runs_from: null,
    runs_to: null,
    url: googleTicketsUrl("Home SW13", "Church Road Barnes"),
    note: "Cosier dinner option",
    is_new: false,
    upcoming: false,
    flexible_arrival: true,
  },
  {
    group_id: "barnes",
    kind: "food",
    title: "Riva",
    venue: "Italian, Church Road",
    area: "Church Road",
    station: null,
    lines: [],
    price_from: null,
    runs_from: null,
    runs_to: null,
    url: googleTicketsUrl("Riva", "Church Road Barnes"),
    note: "Northern edge of the zone",
    is_new: false,
    upcoming: false,
    flexible_arrival: true,
  },
  {
    group_id: "barnes",
    kind: "drinks",
    title: "The Red Lion",
    venue: "Pub, 2 Castelnau",
    area: "Church Road end of Castelnau",
    station: null,
    lines: [],
    price_from: null,
    runs_from: null,
    runs_to: null,
    url: googleTicketsUrl("The Red Lion", "Castelnau Barnes"),
    note: "Victorian pub with nooks, northern edge",
    is_new: false,
    upcoming: false,
    flexible_arrival: true,
  },
];
